# Generated by Django 6.0.1 on 2026-01-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='cohort_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for scoring weights and thresholds'),
        ),
    ]
