# Generated by Django 6.0.2 on 2026-03-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cohort_cohort_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
