# Generated by Django 6.0.1 on 2026-01-30 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('from_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_preferences', to='core.participant')),
                ('to_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_preferences', to='core.participant')),
            ],
            options={
                'verbose_name_plural': 'Preferences',
                'ordering': ['from_participant', 'rank'],
                'indexes': [models.Index(fields=['from_participant', 'rank'], name='matching_pr_from_pa_b53ba3_idx')],
                'unique_together': {('from_participant', 'to_participant')},
            },
        ),
    ]
