# Generated by Django 6.0.1 on 2026-01-30 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cohort_cohort_config'),
        ('matching', '0002_importjob_menteeprofile_mentorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Overall match percentage (0-100)')),
                ('score_breakdown', models.JSONField(default=dict, help_text='Detailed breakdown of score components')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_scores', to='core.cohort')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_scores', to='core.participant')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_scores', to='core.participant')),
            ],
            options={
                'verbose_name_plural': 'Pair Scores',
                'indexes': [models.Index(fields=['cohort', '-score'], name='matching_pa_cohort__5c9143_idx'), models.Index(fields=['mentor', '-score'], name='matching_pa_mentor__8fcc18_idx'), models.Index(fields=['mentee', '-score'], name='matching_pa_mentee__016d95_idx')],
                'unique_together': {('mentor', 'mentee')},
            },
        ),
    ]
