# Generated by Django 6.0.1 on 2026-01-30 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cohort_cohort_config'),
        ('matching', '0003_pairscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('STRICT', 'Strict'), ('EXCEPTION', 'Exception')], max_length=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('objective_summary', models.JSONField(blank=True, default=dict, help_text='Totals, exception counts, total score')),
                ('failure_report', models.JSONField(blank=True, default=dict, help_text='Failure diagnostics when status=FAILED')),
                ('input_signature', models.TextField(blank=True, help_text='Hash of relevant input for traceability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cohort')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Match Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percent', models.IntegerField(help_text='Match percentage (0-100)')),
                ('ambiguity_flag', models.BooleanField(default=False, help_text='Whether this match is ambiguous')),
                ('ambiguity_reason', models.TextField(blank=True, help_text='Explanation of ambiguity if flagged')),
                ('exception_flag', models.BooleanField(default=False, help_text='Whether this match violates policies')),
                ('exception_type', models.CharField(blank=True, help_text='Type of exception if any', max_length=20)),
                ('exception_reason', models.TextField(blank=True, help_text='Explanation of exception if flagged')),
                ('is_manual_override', models.BooleanField(default=False, help_text='Whether this was manually overridden')),
                ('override_reason', models.TextField(blank=True, help_text='Reason for manual override if applicable')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_matches', to='core.participant')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_matches', to='core.participant')),
                ('match_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matching.matchrun')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'unique_together': {('match_run', 'mentor'), ('match_run', 'mentee')},
            },
        ),
        migrations.CreateModel(
            name='ActiveMatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.cohort')),
                ('match_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.matchrun')),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Active Match Runs',
            },
        ),
    ]