# Generated by Django 6.0.2 on 2026-03-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_add_match_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrun',
            name='base_match_run',
            field=models.ForeignKey(blank=True, help_text='Base match run for incremental matching', null=True, on_delete=django.db.models.deletion.SET_NULL, to='matching.matchrun'),
        ),
        migrations.AlterField(
            model_name='matchrun',
            name='mode',
            field=models.CharField(choices=[('STRICT', 'Strict'), ('EXCEPTION', 'Exception'), ('INCREMENTAL', 'Incremental')], max_length=15),
        ),
    ]
